version: 2
jobs:
  deploy-prod:
    docker:
      - image: circleci/node:latest 
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh 

workflows: 
  version: 2 
  validate:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only:
                - master 